### ISSUE TITLE
Saved file needs browser refresh

### ISSUE THREAD

**Issue by davidsavoie1** [fulcrologic/fulcro-tutorial#4]
Hi! I'm really new to Clojure and Clojurescript and maybe there's something really basic I don't get.

I start the tutorial with the `run-tutorial.sh` script, then head to `B_UI_Exercises` in the browser. If I change anything in the `Person` component (such as changing the button "X" to "O"), I see a figwheel reload in the page, but I have to  manually refresh the browser to see the change. Is it the expected behavior? Hot-code reload is working in the introduction devcard...

Thanks!

**Comment by awkay** [comment]
To be honest, I don't remember.  I think the earlier exercises don't because you've not learned how yet....if you read on it might say so.   To be honest, once I created the developers guide and online videos I stopped maintaining this tutorial, but I can't see why it would be broken.  Please join us in Clojurians Fulcro Slack channel for help.

**Comment by awkay** [comment]
I glanced quickly:  What you're seeing is expected.  The devcards are just displaying the cards, and the default defsc components make React components that will not re-render unless props change (as an optimization).  If running them in a real Fulcro app, they would refresh.

**Comment by davidsavoie1** [comment]
Thanks for quick response!
